version: 2.1

jobs:
  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["da:78:60:e6:7b:61:11:43:6e:a0:ce:87:5b:d1:fa:1c"] # You can get this ID in the section where you registered the SSH Key
        - run:
            name: Install dependencies
            command: |
              # install the dependencies needed for your playbook
              apk add --update ansible 
        - run:
            name: Configure server
            command: |
              ansible-playbook -i inventory.txt main-remote.yml

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  configure:
    jobs:
      - configure_infrastructure
